#!/usr/bin/env bash
# symphony-setup デプロイスクリプト。
#
# 行うこと:
#   1. `bun build --compile` で src/index.ts を単一バイナリにコンパイルし
#      ~/.local/bin/symphony-setup へ出力する。
#   2. commands/symphony-loop.md を ~/.claude/commands/symphony-loop.md へ
#      symlink する (冪等)。
#   3. launchd 用 plist を生成し ~/Library/LaunchAgents/ に配置する。
#   4. launchctl でロードする (bootout してから bootstrap し直すことで冪等にする)。
#
# 環境変数:
#   SYMPHONY_INTERVAL_SECONDS  実行間隔 (秒)。デフォルト 1800 (30分)。
#   SKIP_LAUNCHCTL=1           plist の生成・配置までで止め、launchctl のロードは行わない。
#                              (このリポジトリの検証セッションではこちらを使い、実ロードは
#                               ユーザ本人が判断して `bash scripts/deploy.sh` を再実行する)
#
# crontab を使いたい場合は launchd の代わりに以下のような行を `crontab -e` に追加する:
#   */30 * * * * /Users/kziz/.local/bin/symphony-setup >> /Users/kziz/.local/var/log/symphony-setup.log 2>&1

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_PATH="${HOME}/.local/bin/symphony-setup"
COMMAND_SRC="${REPO_ROOT}/commands/symphony-loop.md"
COMMAND_DST="${HOME}/.claude/commands/symphony-loop.md"
LOG_DIR="${HOME}/.local/var/log"
PLIST_LABEL="com.shikibu9419.symphony-setup"
PLIST_PATH="${HOME}/Library/LaunchAgents/${PLIST_LABEL}.plist"
INTERVAL_SECONDS="${SYMPHONY_INTERVAL_SECONDS:-1800}"
# launchd は最小 PATH で起動するため、外部コマンド (ghq, jj, linear) が置かれた
# ディレクトリを明示的に PATH へ通す。Homebrew(/opt/homebrew/bin) と ~/.local/bin を含める。
TOOL_PATH="${HOME}/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

echo "==> [1/4] building ${BIN_PATH}"
mkdir -p "${HOME}/.local/bin"
cd "${REPO_ROOT}"
bun build --compile --outfile "${BIN_PATH}" src/index.ts

echo "==> [2/4] symlinking symphony-loop command"
mkdir -p "$(dirname "${COMMAND_DST}")"
if [ -L "${COMMAND_DST}" ] && [ "$(readlink "${COMMAND_DST}")" = "${COMMAND_SRC}" ]; then
  echo "    already symlinked -> ${COMMAND_SRC}"
else
  ln -sf "${COMMAND_SRC}" "${COMMAND_DST}"
  echo "    symlinked ${COMMAND_DST} -> ${COMMAND_SRC}"
fi

echo "==> [3/4] generating launchd plist (interval=${INTERVAL_SECONDS}s)"
mkdir -p "${LOG_DIR}"
mkdir -p "$(dirname "${PLIST_PATH}")"
cat > "${PLIST_PATH}" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Generated by scripts/deploy.sh — do not edit by hand, re-run the deploy
  script instead. Runs symphony-setup on a fixed interval to sync Linear
  "symphony" projects into tracked repositories.
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_LABEL}</string>

    <!-- 前景実行と同じ環境を確実に継承させるためログインシェル経由で起動する
         (git/jj/linear の解決を含め、対話実行と挙動を揃える保険)。
         なお launchd 下で `ghq create` が固まる問題自体はバイナリ側で ghq 依存を
         排除して解消済み。 -->
    <key>ProgramArguments</key>
    <array>
        <string>/bin/zsh</string>
        <string>-lc</string>
        <string>exec ${BIN_PATH}</string>
    </array>

    <!-- ログインシェルが PATH を張るが、念のため下限としても明示しておく。 -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${TOOL_PATH}</string>
    </dict>

    <!-- StartInterval is in seconds. Change SYMPHONY_INTERVAL_SECONDS and
         re-run scripts/deploy.sh to adjust (default 1800 = 30 minutes). -->
    <key>StartInterval</key>
    <integer>${INTERVAL_SECONDS}</integer>

    <key>RunAtLoad</key>
    <true/>

    <key>StandardOutPath</key>
    <string>${LOG_DIR}/symphony-setup.log</string>

    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/symphony-setup.log</string>

    <key>ProcessType</key>
    <string>Background</string>

    <key>LowPriorityIO</key>
    <true/>
</dict>
</plist>
PLIST
echo "    wrote ${PLIST_PATH}"

if [ "${SKIP_LAUNCHCTL:-0}" = "1" ]; then
  echo "==> [4/4] SKIP_LAUNCHCTL=1 — not loading via launchctl."
  echo "    to load manually later:"
  echo "      launchctl bootout gui/\$(id -u) ${PLIST_PATH} 2>/dev/null || true"
  echo "      launchctl bootstrap gui/\$(id -u) ${PLIST_PATH}"
  echo "      launchctl enable gui/\$(id -u)/${PLIST_LABEL}"
  exit 0
fi

echo "==> [4/4] loading via launchctl"
launchctl bootout "gui/$(id -u)" "${PLIST_PATH}" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "${PLIST_PATH}"
launchctl enable "gui/$(id -u)/${PLIST_LABEL}"
echo "    loaded ${PLIST_LABEL}"
echo "    check status: launchctl print gui/$(id -u)/${PLIST_LABEL}"
echo "    tail logs:    tail -f ${LOG_DIR}/symphony-setup.log"
